"""Changed ad default image something

Revision ID: 48c351a74163
Revises: f1f304bca010
Create Date: 2019-09-12 23:14:26.228340

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48c351a74163'
down_revision = 'f1f304bca010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('default_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ad', 'ad_image', ['default_image_id'], ['id'])
    op.drop_column('ad_image', 'default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_image', sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ad', type_='foreignkey')
    op.drop_column('ad', 'default_image_id')
    # ### end Alembic commands ###
