"""Added Client id Column to ads

Revision ID: 49def87e0a5a
Revises: 48c351a74163
Create Date: 2019-09-12 23:52:17.004266

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '49def87e0a5a'
down_revision = '48c351a74163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ad', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ad', type_='foreignkey')
    op.drop_column('ad', 'client_id')
    # ### end Alembic commands ###
