"""Added View Column to Ads

Revision ID: 6927540cb3d3
Revises: 7ef9c34c1f2d
Create Date: 2019-09-29 16:20:06.715121

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6927540cb3d3'
down_revision = '7ef9c34c1f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'views')
    # ### end Alembic commands ###
