"""Added Summary to ad

Revision ID: 80b33b82ee09
Revises: 869fb6f4a35a
Create Date: 2019-10-10 13:38:32.996990

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '80b33b82ee09'
down_revision = '869fb6f4a35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('summary', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'summary')
    # ### end Alembic commands ###
