"""Added default to AdImage

Revision ID: f1f304bca010
Revises: eb4d798fa9f2
Create Date: 2019-09-11 20:34:48.807066

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f1f304bca010'
down_revision = 'eb4d798fa9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_image', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_image', 'default')
    # ### end Alembic commands ###
